version: '3.8'

name: 'integration-continue'

services:
  jenkins :
    image: jenkins/jenkins:lts
    container_name : jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins_network        

networks:
  jenkins_network:

volumes:
  jenkins_home:
